// src/assets/industriesList.ts

export type Industry = {
  value: string;
  label: string;
};

export const industries: Industry[] = [
  { value: "AIRBNB", label: "Airbnb Hosts / Short-Term Rentals" },
  { value: "ALARM_SYSTEMS", label: "Alarm Systems" },
  { value: "AUTO_DETAILING", label: "Auto Detailing" },
  { value: "AUTO_REPAIR", label: "Auto Repair Shops" },
  { value: "BEAUTY_SALON", label: "Beauty Salons / Barbers" },
  { value: "CAFE", label: "Cafés / Coffee Shops" },
  { value: "CAR_DEALERSHIP", label: "Car Dealerships" },
  { value: "CLEANING", label: "Cleaning Services" },
  { value: "CLOTHING_STORE", label: "Clothing Stores" },
  { value: "COMMERCIAL_SUPPLY", label: "Commercial Supply" },
  { value: "CONVENIENCE_STORE", label: "Convenience Stores" },
  { value: "CONSULTING", label: "Consulting" },
  { value: "DAYCARE", label: "Daycare / Childcare" },
  { value: "DRYWALL", label: "Drywall" },
  { value: "ELECTRICAL", label: "Electrical" },
  { value: "ELECTRONICS_STORE", label: "Electronics Stores" },
  { value: "FENCING", label: "Fencing" },
  { value: "FINANCE", label: "Accounting / Finance" },
  { value: "FIRE_RESTORATION", label: "Fire Restoration" },
  { value: "FITNESS", label: "Gyms / Fitness Studios" },
  { value: "FLOORING", label: "Flooring" },
  { value: "FOOD_TRUCK", label: "Food Trucks" },
  { value: "FURNITURE_STORE", label: "Furniture Stores" },
  { value: "HOME_INSPECTION", label: "Home Inspectors" },
  { value: "HVAC", label: "HVAC" },
  { value: "INSULATION", label: "Insulation" },
  { value: "INSURANCE_CLAIMS", label: "Storm / Insurance Claims" },
  { value: "IT_SERVICES", label: "IT Services" },
  { value: "JEWELRY_STORE", label: "Jewelry Stores" },
  { value: "LANDSCAPING", label: "Landscaping" },
  { value: "LEGAL", label: "Legal Services" },
  { value: "LOGISTICS", label: "Logistics / Delivery" },
  { value: "MANUFACTURING", label: "Manufacturing" },
  { value: "MARKETING", label: "Marketing / Advertising" },
  { value: "MOLD_REMEDIATION", label: "Mold Remediation" },
  { value: "NAIL_SALON", label: "Nail Salons" },
  { value: "OTHER", label: "Other" },
  { value: "PAINTING", label: "Painting" },
  { value: "PEST_CONTROL", label: "Pest Control" },
  { value: "PET_GROOMING", label: "Pet Grooming" },
  { value: "PET_STORE", label: "Pet Stores" },
  { value: "PLUMBING", label: "Plumbing" },
  { value: "POOLS_SPAS", label: "Pools & Spas" },
  { value: "PROPERTY_MANAGEMENT", label: "Property Management" },
  { value: "REAL_ESTATE", label: "Real Estate Agents" },
  { value: "REMODELING", label: "Remodeling" },
  { value: "RESTAURANT", label: "Restaurants" },
  { value: "RETAIL_GENERAL", label: "Retail Stores (General)" },
  { value: "ROOFING", label: "Roofing" },
  { value: "SECURITY_SYSTEMS", label: "Security Systems" },
  { value: "SMART_HOME_SECURITY", label: "Smart Home Security" },
  { value: "SOLAR", label: "Solar" },
  { value: "SUPERMARKET", label: "Supermarkets" },
  { value: "SURVEILLANCE", label: "Surveillance / Cameras" },
  { value: "TIRE_SHOP", label: "Tire Shops" },
  { value: "WAREHOUSING", label: "Warehousing" },
  { value: "WATER_RESTORATION", label: "Water Damage Restoration" },
  { value: "WINDOWS_DOORS", label: "Windows & Doors" },
  { value: "WHOLESALE", label: "Wholesale" },
];
